"""subtask type and priority

Revision ID: 97cae27d3f45
Revises: 
Create Date: 2023-06-12 15:17:57.378580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97cae27d3f45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('SubtaskType', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('Priority', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtask', schema=None) as batch_op:
        batch_op.drop_column('Priority')
        batch_op.drop_column('SubtaskType')

    # ### end Alembic commands ###
